# Generated by Django 5.2 on 2025-07-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirimara_farm', '0002_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='gallery/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
